### ISSUE TITLE
Error in generation: lxml.etree.XMLSyntaxError: Start tag expected, '<' not found

### ISSUE THREAD

**Issue by Mark-Wellings** [akretion/factur-x#17]
Hi, 

I've been trying to get the 'generate_facturx_from_file' to work. Beforehand I validated my XML file and it's fine. When running the below unfortuntately,  no succcess:

    from facturx import generate_facturx_from_file
    import os
    thisdir = os.getcwd()
    regular_pdf_invoice = str(thisdir + '\TEST

    facturx_xml_file = str(thisdir + '\ZUGFeRD-invoice.xml')
    facturx_pdf_invoice = generate_facturx_from_file(regular_pdf_invoice, facturx_xml_file)

The error I get is the following:

    Traceback (most recent call last):
    File "C:\Users\Mark\Desktop\factur-x.py", line 15, in <module>
    facturx_pdf_invoice = generate_facturx_from_file(regular_pdf_invoice, facturx_xml_file)
    File "C:\Users\Mark\AppData\Local\Programs\Python\Python37-32\lib\site-packages\facturx        \facturx.py", line 886, in generate_facturx_from_file
    xml_root = etree.fromstring(xml_string)
    File "src\lxml\etree.pyx", line 3234, in lxml.etree.fromstring
    File "src\lxml\parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
    File "src\lxml\parser.pxi", line 1757, in lxml.etree._parseDoc
    File "src\lxml\parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
    File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
    File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
    File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
    File "<string>", line 1
    lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

The files I use are attached (had to attach the xml as txt). 
[TEST.pdf](https://github.com/akretion/factur-x/files/4114218/TEST.pdf)

[ZUGFeRD-invoice.txt](https://github.com/akretion/factur-x/files/4114223/ZUGFeRD-invoice.txt)

**Comment by schmidtkropp** [comment]
hello everyone, I have the same mistake.
# facturx-pdfgen tmp_splitpdfout / pdfout-GK24848-0021.pdf ZUGFeRD-invoice.xml zug.pdf
works
unfortunately it does not work from the script.

**Comment by hvbtup** [comment]
Seems like a programming error in your code. You'll have to either double the backslash in your literal or use the r'\ZUGFeRD-invoice.xml' form.

**Comment by rockr79** [comment]
Hello,
I have the same error message, does anyone have a solution yet?

**Comment by Andy87730** [comment]
I have the same problem...

**Comment by jonaswndl** [comment]
I have the same problem :))

**Comment by j4s0nmo0n** [comment]
Hello,

There is a sample of code:
self.xml = xml
self.root = etree.fromstring(xml)
 
 it seams that instead of using etree.fromstring(xml), use **etree.parse(xml)**

**Comment by Andy87730** [comment]
works fine - thanks!

**Comment by alexis-via** [comment]
Fixed in release 3.12.
